// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ScreenZoom","status":true,"description":"Zoom screen whose center is specified character or player.","parameters":{}},
{"name":"wasdKeyMZ","status":true,"description":"","parameters":{}},
{"name":"SmartAutoBattle","status":true,"description":"Customize/Refine Actor's battle auto action","parameters":{}},
{"name":"SmoothTouchMove","status":true,"description":"on touch move, player can through events under the player","parameters":{}},
{"name":"2D_Cat_BodyShakeMove","status":true,"description":"v1.0 角色移动时添加晃动身体的效果。","parameters":{"enableOnlyDash":"false"}}
];
